[package]
name = "rtl433-doorbell"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.44"
structopt = "0.3.5"
